### ISSUE TITLE
코드 리뷰

### ISSUE THREAD

**Issue by hrzon** [Omogari/BaeMin#1]
correctness는 정확한 것 같습니다! 잘 짜셨어요.

리뷰해드릴게 3가지가 있습니다.

첫 번째로는, zeroAndOne 대신 binaryStr이라는 변수명이 더 낫지 않을까 싶네요.

잘 아시는 것처럼 프로그래밍 세계에서 And는 보통 사람들이 쓰는 And의 의미와 다르기 때문에, 그리고 문제에서 '스트링에 2진수가 들어있다' 라고 했으니 binaryStr이 더 나을것같아요.

두 번째는 end변수에 관해서입니다. for loop의 탈출 조건에 length()를 호출하면 반복을 할 때마다 length()를 호출하게 되니 end라는 변수에 length()의 리턴값을 담아서 사용한 것으로 이해했습니다.

end라는 이름은 너무 포괄적이라서, lastDigitIdx라는 이름이 더 좋을 것 같습니다.

더 나아가서, 탈출조건에 length()를 호출하게 해도 컴파일러가 최적화를 하면 결국 우빈님 코드를 최적화한 것과 같은 결과물을 만들어낼거에요.

length()라는 메소드는 string 객체 내부의 length 변수의 값을 리턴하는 간단한 getter 메소드입니다. 컴파일러는 메소드를 inline 코드로 바꿀 겁니다. 이렇게 되면 end변수를 사용하는 우빈님 코드와 완전히 같아지게 됩니다.

여기서 더 최적화를 하지 않는다면, for loop의 탈출조건을 검사할 때마다 메모리의 length변수 공간에 접근해서 값을 읽어와 레지스터에 저장하는 과정을 반복합니다. 최적화를 하면, 읽어온 length변수의 값을 레지스터에 저장한 뒤 그 값을 계속 사용하기 때문에 메모리의 length변수에 한 번만 접근하게 됩니다.

처음부터 최적화가 필요없는 코드를 작성하는 것도 정말 좋지만, 컴파일러가 어떻게 최적화를 하는지 이해해서 가독성이 높은 코드를 작성하는 것도 좋습니다. 극적인 성능 향상이 없다면 가독성이 높은 코드가 약간 더 빠른 코드보단 훨씬 낫습니다(실무에서). 코딩테스트라면 본인의 능력을 어필할 수 있는 방향으로 선택하면 될 것 같습니다.

마지막으로는 Tab대신 space로 indentation을 하는걸 추천하는데, 이건 취향차이라고 볼 수 있어서 뭐가 답이다라고 말은 못드려요. Tab의 size는 설정하는대로 달라지기 때문에 모든 상황에서 같은 모양의 코드를 보여준다고 장담할 수 없어서 저는 space를 선호합니다. 배민 내부 코딩스타일 가이드에서도 tab대신 space를 쓰도록 하고 있습니다.

tab size는 보통 4칸을 쓸 텐데, 구글에서는 2칸으로 하기 때문에 저는 2칸으로 합니다. 한 줄에 좀 더 많은 코드를 볼 수 있어서 좋아요.

**Comment by hrzon** [comment]
아 그리고 불편하더라도 주석은 영어로 다는 습관을 들이시는게 우빈님의 성장에 도움이 될거에요. vim에서 한글 입력하는게 불편하기도 하고...

**Comment by hrzon** [comment]
우빈님 코드 바탕으로 제가 코딩테스트에서 짰던 코드를 작성해봤습니다. 우빈님 코드가 훨씬 깔끔하네요 ㅋㅋㅋ

```cpp
#include <iostream>
#include <string>
#include <cassert>

using namespace std;

int main(void) {

  string input;
  int cnt = 0, msb_idx; // msb = most significant bit

  cout << "문자열[0/1] 입력 : ";
  getline(cin, input);

  msb_idx = input.find('1');

  if (msb_idx == -1) {
    // do nothing
  } else {        
    // Remove leading zeros
    string binary_str = input.substr(msb_idx);

    while(binary_str.length() > 1 || binary_str.back() == '1' ) {
      if(binary_str.back() == '1') {
        // If it is an odd number, minus 1

        // Modify last character
        *(binary_str.rbegin()) = '0';
      } else {
        // If it is an even number,
        // do shift operation instead of dividing it by 2
        assert(binary_str.back() == '0');
        binary_str.pop_back();
      }
      cnt++;
    }
  }

  cout << "연산의 횟수 : " << cnt << "회" << endl;
  
  return 0;
}
```

**Comment by Omogari** [comment]
> correctness는 정확한 것 같습니다! 잘 짜셨어요.
> 
> 리뷰해드릴게 3가지가 있습니다.
> 
> 첫 번째로는, zeroAndOne 대신 binaryStr이라는 변수명이 더 낫지 않을까 싶네요.
> 
> 잘 아시는 것처럼 프로그래밍 세계에서 And는 보통 사람들이 쓰는 And의 의미와 다르기 때문에, 그리고 문제에서 '스트링에 2진수가 들어있다' 라고 했으니 binaryStr이 더 나을것같아요.
> 
> 두 번째는 end변수에 관해서입니다. for loop의 탈출 조건에 length()를 호출하면 반복을 할 때마다 length()를 호출하게 되니 end라는 변수에 length()의 리턴값을 담아서 사용한 것으로 이해했습니다.
> 
> end라는 이름은 너무 포괄적이라서, lastDigitIdx라는 이름이 더 좋을 것 같습니다.
> 
> 더 나아가서, 탈출조건에 length()를 호출하게 해도 컴파일러가 최적화를 하면 결국 우빈님 코드를 최적화한 것과 같은 결과물을 만들어낼거에요.
> 
> length()라는 메소드는 string 객체 내부의 length 변수의 값을 리턴하는 간단한 getter 메소드입니다. 컴파일러는 메소드를 inline 코드로 바꿀 겁니다. 이렇게 되면 end변수를 사용하는 우빈님 코드와 완전히 같아지게 됩니다.
> 
> 여기서 더 최적화를 하지 않는다면, for loop의 탈출조건을 검사할 때마다 메모리의 length변수 공간에 접근해서 값을 읽어와 레지스터에 저장하는 과정을 반복합니다. 최적화를 하면, 읽어온 length변수의 값을 레지스터에 저장한 뒤 그 값을 계속 사용하기 때문에 메모리의 length변수에 한 번만 접근하게 됩니다.
> 
> 처음부터 최적화가 필요없는 코드를 작성하는 것도 정말 좋지만, 컴파일러가 어떻게 최적화를 하는지 이해해서 가독성이 높은 코드를 작성하는 것도 좋습니다. 극적인 성능 향상이 없다면 가독성이 높은 코드가 약간 더 빠른 코드보단 훨씬 낫습니다(실무에서). 코딩테스트라면 본인의 능력을 어필할 수 있는 방향으로 선택하면 될 것 같습니다.
> 
> 마지막으로는 Tab대신 space로 indentation을 하는걸 추천하는데, 이건 취향차이라고 볼 수 있어서 뭐가 답이다라고 말은 못드려요. Tab의 size는 설정하는대로 달라지기 때문에 모든 상황에서 같은 모양의 코드를 보여준다고 장담할 수 없어서 저는 space를 선호합니다. 배민 내부 코딩스타일 가이드에서도 tab대신 space를 쓰도록 하고 있습니다.
> 
> tab size는 보통 4칸을 쓸 텐데, 구글에서는 2칸으로 하기 때문에 저는 2칸으로 합니다. 한 줄에 좀 더 많은 코드를 볼 수 있어서 좋아요.

**Comment by Omogari** [comment]
> correctness는 정확한 것 같습니다! 잘 짜셨어요.
> 
> 리뷰해드릴게 3가지가 있습니다.
> 
> 첫 번째로는, zeroAndOne 대신 binaryStr이라는 변수명이 더 낫지 않을까 싶네요.
> 
> 잘 아시는 것처럼 프로그래밍 세계에서 And는 보통 사람들이 쓰는 And의 의미와 다르기 때문에, 그리고 문제에서 '스트링에 2진수가 들어있다' 라고 했으니 binaryStr이 더 나을것같아요.
> 
> 두 번째는 end변수에 관해서입니다. for loop의 탈출 조건에 length()를 호출하면 반복을 할 때마다 length()를 호출하게 되니 end라는 변수에 length()의 리턴값을 담아서 사용한 것으로 이해했습니다.
> 
> end라는 이름은 너무 포괄적이라서, lastDigitIdx라는 이름이 더 좋을 것 같습니다.
> 
> 더 나아가서, 탈출조건에 length()를 호출하게 해도 컴파일러가 최적화를 하면 결국 우빈님 코드를 최적화한 것과 같은 결과물을 만들어낼거에요.
> 
> length()라는 메소드는 string 객체 내부의 length 변수의 값을 리턴하는 간단한 getter 메소드입니다. 컴파일러는 메소드를 inline 코드로 바꿀 겁니다. 이렇게 되면 end변수를 사용하는 우빈님 코드와 완전히 같아지게 됩니다.
> 
> 여기서 더 최적화를 하지 않는다면, for loop의 탈출조건을 검사할 때마다 메모리의 length변수 공간에 접근해서 값을 읽어와 레지스터에 저장하는 과정을 반복합니다. 최적화를 하면, 읽어온 length변수의 값을 레지스터에 저장한 뒤 그 값을 계속 사용하기 때문에 메모리의 length변수에 한 번만 접근하게 됩니다.
> 
> 처음부터 최적화가 필요없는 코드를 작성하는 것도 정말 좋지만, 컴파일러가 어떻게 최적화를 하는지 이해해서 가독성이 높은 코드를 작성하는 것도 좋습니다. 극적인 성능 향상이 없다면 가독성이 높은 코드가 약간 더 빠른 코드보단 훨씬 낫습니다(실무에서). 코딩테스트라면 본인의 능력을 어필할 수 있는 방향으로 선택하면 될 것 같습니다.
> 
> 마지막으로는 Tab대신 space로 indentation을 하는걸 추천하는데, 이건 취향차이라고 볼 수 있어서 뭐가 답이다라고 말은 못드려요. Tab의 size는 설정하는대로 달라지기 때문에 모든 상황에서 같은 모양의 코드를 보여준다고 장담할 수 없어서 저는 space를 선호합니다. 배민 내부 코딩스타일 가이드에서도 tab대신 space를 쓰도록 하고 있습니다.
> 
> tab size는 보통 4칸을 쓸 텐데, 구글에서는 2칸으로 하기 때문에 저는 2칸으로 합니다. 한 줄에 좀 더 많은 코드를 볼 수 있어서 좋아요.

친절한 코드리뷰 감사드려요!
* 2번에 대한 질문인데, 저도 처음에 end 변수로 빼려던게 아니라 for loop 안에 직접 함수호출을 하려 했는데, 무슨일인지 " '<': signed 또는 unsigned가 일치하지 않습니다. " 라는 에러가 떠서
해결을 못하고 그냥 뺐던 거였거든요. 혹시 해결방법을 알 수 있을까요?

**Comment by hrzon** [comment]
그건 컴파일러에서 signed, unsigned 변수를 체크하는 옵션이 켜져있어서 그렇습니다.

컴파일러의 warning 기준은 최대로 높혀서 사용하는 것이 좋아요. 불편하겠지만, 컴파일러의 경고에서 배울 수 있는 것들이 많습니다. 저는 컴파일러 옵션에 `-Wall -Wextra -Wpedantic`를 넣어서 사용합니다 (gcc 컴파일러).

<http://www.cplusplus.com/reference/string/string/length/>

length() 메소드는 size_t 타입을 리턴하는데, size_t는 32bit 아키텍쳐에서는 4바이트, 64bit에서는 8바이트 정수입니다. 그리고 부호가 없구요(unsigned).

<https://hashcode.co.kr/questions/754/size_t는-정확히-어떤-타입인가요>

For loop에서 선언한 `i`는 `signed int`입니다. `stdint.h`를 include하고 `int32_t` 타입과 `uint64_t`타입의 변수를 비교(<, ==, > 등의 비교연산자) 해보면 같은 경고가 나오는 것을 볼 수 있을겁니다.
